import 'package:flutter/material.dart';
import 'package:flutterapp/simpegapp/generatedandroid1widget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid1widget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid1widget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid1widget/generated/GeneratedLupaPasswordWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid1widget/generated/GeneratedUsernameWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid1widget/generated/GeneratedLOGINWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid1widget/generated/GeneratedLambang_Kabupaten_Solok_Selatan1Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid1widget/generated/GeneratedAsn3Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid1widget/generated/GeneratedSIMPEGSOLSELWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid1widget/generated/GeneratedGroup12Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid1widget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid1widget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid1widget/generated/GeneratedGreentonesgradientbackground_2321483761671Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid1widget/generated/GeneratedBKPSDMPEMKABSOLOKSELATANWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid1widget/generated/GeneratedRememberMeWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid1widget/generated/GeneratedRectangle2Widget.dart';

/* Frame Android - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 492.0,
                child:
                    GeneratedGreentonesgradientbackground_2321483761671Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 187.0,
                child: GeneratedAsn3Widget(),
              ),
              Positioned(
                left: 119.0,
                top: 82.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 126.0,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 169.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 498.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 129.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 43.0,
                child: GeneratedLOGINWidget(),
              ),
              Positioned(
                left: 67.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 37.0,
                child: GeneratedSIMPEGSOLSELWidget(),
              ),
              Positioned(
                left: 326.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 291.0,
                height: 48.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 326.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 291.0,
                height: 48.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 63.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 21.0,
                child: GeneratedUsernameWidget(),
              ),
              Positioned(
                left: 119.0,
                top: 493.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 48.0,
                child: GeneratedGroup12Widget(),
              ),
              Positioned(
                left: 63.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 21.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 129.0,
                top: 548.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 18.0,
                child: GeneratedLupaPasswordWidget(),
              ),
              Positioned(
                left: 73.0,
                top: 455.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 18.0,
                child: GeneratedRememberMeWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 457.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 12.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 139.0,
                top: 98.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 95.0,
                child: GeneratedLambang_Kabupaten_Solok_Selatan1Widget(),
              ),
              Positioned(
                left: 67.0,
                top: 605.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 18.0,
                child: GeneratedBKPSDMPEMKABSOLOKSELATANWidget(),
              )
            ]),
      ),
    ));
  }
}
