import 'package:flutter/material.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedGroup1Widget1.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedWELCOMEWidget1.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedRectangle14Widget1.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedAsn2Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedKepalaDinasWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedEllipse1Widget1.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedRectangle7Widget.dart';

/* Frame Android - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 197.0,
                child: GeneratedAsn2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: -2.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 245.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 118.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 528.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 117.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 125.0,
                child: GeneratedEllipse1Widget1(),
              ),
              Positioned(
                left: 123.0,
                top: 189.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 33.0,
                child: GeneratedWELCOMEWidget1(),
              ),
              Positioned(
                left: 139.0,
                top: 217.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 18.0,
                child: GeneratedKepalaDinasWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 579.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 61.0,
                child: GeneratedRectangle14Widget1(),
              ),
              Positioned(
                left: 60.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 38.0,
                child: GeneratedGroup1Widget1(),
              ),
              Positioned(
                left: 160.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 38.0,
                child: GeneratedGroup3Widget(),
              ),
              Positioned(
                left: 263.0,
                top: 596.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedGroup2Widget(),
              ),
              Positioned(
                left: 51.0,
                top: 587.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 3.0,
                child: GeneratedLine1Widget(),
              )
            ]),
      ),
    ));
  }
}
