import 'package:flutter/material.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedPerson_pinWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedRectangle22Widget1.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedAktifitasWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedEllipse4Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedAccount_circleWidget1.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedFingerprintWidget1.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedGroup17Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedNotifikasiWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedFlight_takeoffWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedAssignmentWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedHourglass_emptyWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedProfilWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedWELCOMEWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedNONIPWidget2.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedGroup13Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedGroup15Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedAccount_circleWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedAccount_circleWidget2.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedGroup16Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedAsn1Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedFingerprintWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedNotifications_activeWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedRectangle26Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedPerm_identityWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedPEGAWAIBERULANGTAHUNHARIINIWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedNotifications_noneWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedGroup11Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedKelapaDinasWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid2widget/generated/GeneratedEllipse1Widget.dart';

/* Frame Android - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 4.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 352.0,
                height: 181.0,
                child: GeneratedAsn1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: -2.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 182.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 528.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 76.0,
                top: 342.0,
                right: null,
                bottom: null,
                width: 242.0,
                height: 41.0,
                child: GeneratedRectangle26Widget(),
              ),
              Positioned(
                left: 117.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 125.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 123.0,
                top: 189.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 33.0,
                child: GeneratedWELCOMEWidget(),
              ),
              Positioned(
                left: 139.0,
                top: 217.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 18.0,
                child: GeneratedKelapaDinasWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 579.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 61.0,
                child: GeneratedGroup18Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 589.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 38.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 278.0,
                top: 248.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 78.0,
                child: GeneratedGroup13Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 248.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 78.0,
                child: GeneratedRectangle19Widget(),
              ),
              Positioned(
                left: 97.0,
                top: 248.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 78.0,
                child: GeneratedRectangle20Widget(),
              ),
              Positioned(
                left: 12.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 146.0,
                child: GeneratedRectangle22Widget1(),
              ),
              Positioned(
                left: 243.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 112.0,
                child: GeneratedGroup17Widget(),
              ),
              Positioned(
                left: 133.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 112.0,
                child: GeneratedGroup15Widget(),
              ),
              Positioned(
                left: 143.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 72.0,
                child: GeneratedAccount_circleWidget(),
              ),
              Positioned(
                left: 248.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 72.0,
                child: GeneratedAccount_circleWidget1(),
              ),
              Positioned(
                left: 23.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 112.0,
                child: GeneratedGroup16Widget(),
              ),
              Positioned(
                left: 187.0,
                top: 248.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 78.0,
                child: GeneratedRectangle21Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 16.0,
                child: GeneratedGroup9Widget(),
              ),
              Positioned(
                left: 117.0,
                top: 297.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 16.0,
                child: GeneratedGroup10Widget(),
              ),
              Positioned(
                left: 206.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 32.0,
                child: GeneratedGroup11Widget(),
              ),
              Positioned(
                left: 81.0,
                top: 356.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 20.0,
                child: GeneratedPEGAWAIBERULANGTAHUNHARIINIWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 39.0,
                child: GeneratedEllipse3Widget(),
              ),
              Positioned(
                left: 44.0,
                top: 352.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedNotifications_activeWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 37.0,
                child: GeneratedFingerprintWidget(),
              ),
              Positioned(
                left: 117.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 37.0,
                child: GeneratedPerson_pinWidget(),
              ),
              Positioned(
                left: 209.0,
                top: 255.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 37.0,
                child: GeneratedFlight_takeoffWidget(),
              ),
              Positioned(
                left: 297.0,
                top: 261.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 37.0,
                child: GeneratedAssignmentWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 72.0,
                child: GeneratedAccount_circleWidget2(),
              ),
              Positioned(
                left: 45.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 21.0,
                child: GeneratedNONIPWidget2(),
              ),
              Positioned(
                left: 144.0,
                top: 554.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 66.0,
                child: GeneratedEllipse4Widget(),
              ),
              Positioned(
                left: 155.0,
                top: 564.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 46.0,
                child: GeneratedFingerprintWidget1(),
              ),
              Positioned(
                left: 85.0,
                top: 589.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedHourglass_emptyWidget(),
              ),
              Positioned(
                left: 76.0,
                top: 616.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 19.0,
                child: GeneratedAktifitasWidget(),
              ),
              Positioned(
                left: 247.0,
                top: 589.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedNotifications_noneWidget(),
              ),
              Positioned(
                left: 233.0,
                top: 616.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 19.0,
                child: GeneratedNotifikasiWidget(),
              ),
              Positioned(
                left: 310.0,
                top: 589.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPerm_identityWidget(),
              ),
              Positioned(
                left: 310.0,
                top: 616.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 19.0,
                child: GeneratedProfilWidget(),
              )
            ]),
      ),
    ));
  }
}
